### ISSUE TITLE
Add option to drop Otel native processed metrics

### ISSUE THREAD

**Issue by rogercoll** [elastic/opentelemetry-lib#97]
The current remappers do not override the processed metrics, but they insert new metrics. In that sense, we end up having duplicated metric values but with different name. For example, `k8s.pod.cpu_limit_utilization` vs `kubernetes.pod.cpu.usage.limit.pct`.

This hasn’t been an issue so far because our primary focus has been on the ecs format, with metrics being sent by the Elasticsearch exporter configured in ecs mode. However, as we begin transitioning to the native Otel mode, we now face the challenge of having to support both metrics formats in Kibana:

- ECS: Inventory
- Otel: K8s Otel native dashboards

The problem when not overriding the current metrics is that both metrics formats will be forwarded to the same `elasticsearch` exporter, and depending on its configuration they will be formatted: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticsearchexporter#elasticsearch-document-mapping

Let's take this configuration:

```yaml
exporters:
  elasticsearch:
    mode: ecs
pipelines:
  metrics:
    receivers: [kubectl]
    processors: [elasticinframetrics]
    exporters: [elasticsearch]
```

As the elasticsearch exporter is configured with ecs mode, all metrics (native and added ones) processed by the EIMP processor will be formatted.

It would be great to have an option in the remappers, so processors override the metrics instead of inserting them. This is the pipeline we have in mind:

```yaml
elasticinframetric:
  override: true
exporters:
  elasticsearch/ecs:
    mode: ecs
  elasticsearch/otel:
    mode: otel
pipelines:
  metrics/ecs:
    receivers: [kubectl]
    processors: [elasticinframetrics]
    exporters: [elasticsearch/ecs]
  metrics/otel:
    receivers: [kubectl]
    processors: []
    exporters: [elasticsearch/otel]
```

**Comment by ishleenk17** [comment]
My initial thought on this: 
EIMP is not meant to be used in OTEL mode of exporter.
The whole point of this processor was to be used along with ecs mode of exporter to do the required translations. 

Rest, I would go through the issue in details.

**Comment by tetianakravchenko** [comment]
@rogercoll I've tested use of the `elasticinframetrics` with the `mode: otel`:
```
    exporters:
        elasticsearch:
            mode: otel
    processors:
        elasticinframetrics:
          add_system_metrics: true
          add_k8s_metrics: true
    pipelines:
      metrics:
        receivers: [kubectl, hostmetrics]
        processors: [elasticinframetrics]
        exporters: [elasticsearch]
```
(also including the hostmetrics part as system metrics are also needed for the Inventory UI)
Outcome:
1. created datastreams include `*.otel` in the end:
![Image](https://github.com/user-attachments/assets/4b1ea0be-8124-4ada-a739-f2a3e48956ab)

-> Inventory UI will not work because of that

2. As an example I've checked `kubernetes.pod.otel` datastream - there are only transformed metrics, but with `metrics.*` prefix
![Image](https://github.com/user-attachments/assets/58203793-a263-41de-997e-f09fc7d65e84)

3. In logs of the collector there are lots of `failed to index document` for the otel k8s (and system) metrics:
```
2024-09-19T15:23:39.791Z	error	elasticsearchexporter@v0.108.0/bulkindexer.go:332	failed to index document	{"kind": "exporter", "data_type": "metrics", "name": "elasticsearch", "index": "metrics-generic.otel-default", "error.type": "document_parsing_exception", "error.reason": "[1:164] Can't find dynamic template for dynamic template name [gauge_long] of field [metrics.k8s.container.restarts]"}
```

**Comment by tetianakravchenko** [comment]
Test with config:
```
processors:
  elasticinframetrics:
     add_system_metrics: true
     add_k8s_metrics: true
exporters:
  elasticsearch/otel:
     mapping:
        mode: otel
  elasticsearch/ecs:
    mapping:
         mode: ecs
pipelines:
  metrics/ecs:
    receivers: [kubectl, hostmetrics]
    processors: [elasticinframetrics]
    exporters: [elasticsearch/ecs]
  metrics/otel:
    receivers: [kubectl, hostmetrics]
    processors: []
    exporters: [elasticsearch/otel]
```
Note: we need to split pipelines only for daemonset, for deployment we can use `elasticsearch/otel` only.

Outcome:
1. It is needed to install assets for system and k8s integration.
2. Inventory page is relying on metrics stored in 9 datasteams: `kubernetes.pod`, `system.process`, `system.network`, `system.filesystem`, `system.diskio`, `system.cpu`, `system.load`, `system.memory`, `system.process.summary`
3. metrics coming from `mode: ecs` are stored in `generic` datastream, from `mode: otel`  - in `generic.otel` datastream. They are not overlapping.

**Comment by gizas** [comment]
Just to double-down on previous comment, was testing in code today and I see that the remapper just creates another document with tranformed kubernetes.* metrics and nothing else (see test [here](https://github.com/elastic/opentelemetry-lib/blob/4370667230667af3e23d7253d9d8f0bf8b9235ef/remappers/kubernetesmetrics/k8smetrics_test.go#L89) where the `k8s.pod.test` wont be available in final document)

The `generic` datastream can be removed/ dropped ! It contains the kubelet related metrics that come from mode:ecs pipeline.
Same copy of metrics is present in `generic.otel`

**Note:**
The only available option to implement the drop of rest of metrics I think can be not to return the mb object [here](https://github.com/elastic/opentelemetry-collector-components/blob/main/processor/elasticinframetricsprocessor/processor.go#L71). The remapper would still have taken place in lines above.

**Comment by rogercoll** [comment]
> we need to split pipelines only for daemonset

My main concern is regarding metrics duplication, at the moment if we configure the `kubeletstats` + `elasticinframetrics` we end up with the same metrics but with different names (no matter the elasticsearch exporter mode): `k8s.*` and `kubernetes.*`. 
These are the metrics that will be ingested with the following configuration:
 
```
pipelines:
  metrics/ecs:
    receivers: [kubectl, hostmetrics]
    processors: [elasticinframetrics] ---> `k8s.*`,  `kubernetes.*`, `system.*` and `system in ecs format`
    exporters: [elasticsearch/ecs]
  metrics/otel:
    receivers: [kubectl, hostmetrics]
      processors: [] ---> `k8s.*`,  `system.*`
    exporters: [elasticsearch/otel]
``` 

Note that the `k8s.*` and the `system.*` metrics will be duplicated but exported with different modes. @tetianakravchenko @gizas is this the expected behavior? Which metrics do we need for the inventory?

 If we only need ECS metrics, I think the `elasticinframetrics` should drop the otel metrics and just produce the ECS ones: 

```
pipelines:
  metrics/ecs:
    receivers: [kubectl, hostmetrics]
    processors: [elasticinframetrics] --->   `kubernetes.*` and `system in ecs format`
    exporters: [elasticsearch/ecs]
  metrics/otel:
    receivers: [kubectl, hostmetrics]
      processors: [] ---> `k8s.*`,  `system.*`
    exporters: [elasticsearch/otel]
```
